# Generated by Django 4.1 on 2022-09-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_number', models.IntegerField(max_length=5)),
                ('Student_id', models.CharField(max_length=16)),
                ('Student_password', models.CharField(max_length=20)),
            ],
        ),
    ]
