# Generated by Django 4.1 on 2022-09-03 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ksum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Student_number',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ksum.user')),
            ],
        ),
    ]
