# Generated by Django 4.1 on 2022-09-04 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksum', '0003_borrow_umbrella_number_borrow_umbrella_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='umbrella_return_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 18, 17, 29, 54, 166252)),
        ),
        migrations.AlterField(
            model_name='user',
            name='Student_number',
            field=models.IntegerField(),
        ),
    ]
