# Generated by Django 4.1 on 2022-09-05 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksum', '0004_alter_borrow_umbrella_return_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Student_id',
        ),
        migrations.AlterField(
            model_name='borrow',
            name='umbrella_return_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 19, 16, 59, 16, 58616)),
        ),
    ]
