# Generated by Django 4.0.6 on 2022-09-09 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksum', '0006_remove_borrow_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='borrowed_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 9, 11, 10, 35, 77877)),
        ),
    ]
