# Generated by Django 4.0.6 on 2022-09-09 02:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ksum', '0007_borrow_borrowed_by_alter_borrow_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='return_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
